version: 2

sources:
  - name: exercise_data
    description: Source table from Snoflake
    database: KEBOOLA_7127
    schema: WORKSPACE_15661914
    tables:
    - name: EXERCISE_FACT
    - name: V_EXERCISE_STAR
    - name: ACTIVITY_TYPE_DIM
    - name: WALKING_DATA

models:
    - name: exercise_ru_day_fact
      description: "first dbt fact table"
      columns:
          - name: date_done
            description: "date exercise was done"
          - name: activity_type_id
            description: "id of the activity to map to the dim"
          - name: activity_count
            description: "count of activity performed"
    - name: exercise_pivot_fact
      description: "first dbt jinja using fact table"
      columns:
          - name: date_done
            description: "date exercise was done"
          - name: pull_up_count
            description: "total pull ups"
          - name: crunch_count
            description: "total crunches"
          - name: push_up_count
            description: "total push ups "
          - name: plank_time_count
            description: "total plank time"
          - name: dumbbells_count
            description: "total dumbells lifted"
          - name: box_jump_count
            description: "total box jumps"
    - name: exercise_all_fact
      description: "Roll Up fact pivoted for stats"
      columns:
          - name: pull_up_count
            description: "total pull ups"
          - name: crunch_count
            description: "total crunches"
          - name: push_up_count
            description: "total push ups "
          - name: plank_time_count
            description: "total plank time"
          - name: dumbbells_count
            description: "total dumbells lifted"
          - name: box_jump_count
            description: "total box jumps"
