version: 2

sources:
  - name: exercise_data
    description: Source table from Snoflake
    database: KEBOOLA_7127
    schema: WORKSPACE_15661914
    tables:
    - name: EXERCISE_FACT

models:
    - name: exercise_ru_day_fact
      description: "first dbt fact table"
      columns:
          - name: date_done
            description: "date exercise was done"
          - name: activity_type_id
            description: "id of the activity to map to the dim"
          - name: activity_count
            description: "count of activity performed"
 